rm JULIA_JSON

diff --git a/julia b/julia
--- a/julia
+++ b/julia
@@ -1,20 +1,22 @@
 #!/bin/bash
-set -euo pipefail
+set -euxo pipefail
 
-JULIA_JSON=$(curl -fsSL https://julialang-s3.julialang.org/bin/versions.json)
+cd "$(mktemp -d)" || { echo "Failed to move to tempdir"; exit 1; }
+
+curl -L https://julialang-s3.julialang.org/bin/versions.json -o versions.json
 JULIA_VERSION=$(
-    echo "$JULIA_JSON" |
+    cat versions.json |
     jq -r 'keys | .[]' |
     grep -v - |
     sort --version-sort |
     tail -n 1
 )
 JULIA_URL=$(
-    echo "$JULIA_JSON" |
+    cat versions.json |
     jq -r --arg jv "$JULIA_VERSION" '.[$jv].files[] | select(.triplet == "x86_64-linux-gnu") | .url'
 )
+rm -f versions.json
 
-cd "$(mktemp -d)" || { echo "Failed to move to tempdir"; exit 1; }
 curl -L "$JULIA_URL" -o julia.tar.gz
 
 mkdir -p julia
